### PR TITLE
Fix WARP and WARP k-OS losses

### PR DESCRIPTION
**Pull request by danieljl**
Should they be implemented this way?

### CODE REVIEW

**Comment by maciejkula** [comment]
You will note that all the builds failed, so my guess would be: no, they should not be implemented this way.

More seriously, have you ran any evaluation of your proposed changes? What are the results?

**Comment by danieljl** [comment]
Oops, I forgot to handle if there isn't any negative item. All the tests should pass now. I don't know why `tests/test_movielens.py::test_logistic_precision` failed on CircleCI only. I didn't even touch the code of logistic loss.

I've tried to train using my own dataset. The precision and NDCG scores were essentially the same as those of the original implementation.

Basically, my changes follow the original papers of WARP and WARP k-OS.

In the paper a random negative sample is picked from the set of negative items, while LightFM samples it from the whole items: `negative_item_id = (rand_r(&random_states[{thread_num}]) % item_features.rows)`. It can be implemented this way as long as the positive item picked is not counted as a "wrong" sample, i.e. `sampled` is not incremented when the positive item is picked.

The second change I made is regarding the loss computation. In WARP paper the numerator is <number of labels/items> - 1 because there is only one true label. If there are more than one label, it should be <number of labels/items> - <number of negative items> as proposed in WARP k-OS paper.

**Comment by maciejkula** [comment]
Thanks for the explanation.

I think changing the numerator is OK. Changing the way we increment `sampled` I am less sure about: it introduces a nasty corner case for users who have a lot of positive interactions.

More generally, do you think there are tangible benefits to making these changes? Unless we can demonstrate benefits, there doesn't seem to be a clear case for them.

**Comment by maciejkula** [comment]
Closing due to inactivity.

**Pull request closed without merging**
