### PR TITLE
Added predict_score (modelled on predict_rank)

### PR DESCRIPTION
**Pull request by paoloRais**
I wrote a method predict_score (modelled upon predict_rank).
The aim is to output the model scores as done by the predict method, but being able to do so for a (no_users, no_items) input matrix.

### CODE REVIEW

**Comment by maciejkula** [comment]
Thanks!

You'll need to run `python setup.py cythonize` and commit the .c files before CI can build the new version.

**Comment by paoloRais** [comment]
The CircleCl fail seems unrelated.

**Comment by maciejkula** [comment]
The code looks good. Could you explain why this would be more useful than just `predict`? My preference would be to expand `predict` to make it more flexible (if necessary), rather than adding another method to the API.

**Comment by paoloRais** [comment]
I wrote this code to be able to compute the scores for on a (no_users, no_items) matrix, with a syntax as close as possible as predict_ranks.

The advantage over using predict is that the user representation is computed only once for each user in the matrix, so it should be faster for large matrices than predict_lightfm (which re-computes both the user and item representations for each user-item pair).

I agree that is also possible to extend predict to obtain the same effect (using predict_scores instead of predict_lightfm), I will look into it if you think it is a better solution.

**Comment by maciejkula** [comment]
I see, computing representations only once is an advantage.

What do you think about the following?

1. Accept sparse matrices as well as current arguments (for backwards compatibility)
2. Accept an flag which would cause all needed user and item representations to be precomputed before computing all the scores. This flag could also be useful for `predict_ranks`.

**Comment by paoloRais** [comment]
Sounds good. I should have some time to look into that in the next days.

**Pull request closed without merging**
