### PR TITLE
Update Docker instructions.

### PR DESCRIPTION
**Pull request by maciejkula**
The gist of the problem is that the current directory was mounted by default, and it didn't have the compiled extensions.

https://github.com/lyst/lightfm/issues/211

### CODE REVIEW

**Comment by HarlanH** [comment]
Well, it's better! But...

```
✔ ~/Development/lightfm [docker_instructions|…1]
16:08 $ docker-compose run lightfm py.test -x lightfm/tests/
============================= test session starts =============================
platform linux -- Python 3.6.1, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/lightfm, inifile:
collected 56 items

lightfm/tests/test_api.py ................
lightfm/tests/test_datasets.py .✘-KILL ~/Development/lightfm [docker_instructions|…1]
16:09 $ docker-compose run lightfm jupyter notebook lightfm/examples/movielens/example.ipynb --ip=0.0.0.0
[I 20:09:15.896 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[C 20:09:15.963 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.
✘-1 ~/Development/lightfm [docker_instructions|…1]
```

So, it looks like test_datasets is maybe timing out and getting killed. And the movielens example (which does need the path change too, by the way!) is failing with another issue.

**Comment by maciejkula** [comment]
One of the dataset tests is highly memory intensive. You are simply running out of memory.

What is the movielens issue?

**Comment by HarlanH** [comment]
Oh, scroll right in my code block above -- it looks like I'm getting some sort of warnings about running as root, but then the process is existing with error code 1, and `docker ps` shows nothing running.

I'm relatively new to docker, so I'm probably not being as clear as I ought to be...

**Comment by maciejkula** [comment]
@HarlanH I've updated the instructions for launching a notebook server.

**Comment by HarlanH** [comment]
@maciejkula Great, works like a charm, thanks!

**Comment by maciejkula** [comment]
Great!

**Pull request merged**
